### ISSUE TITLE
expectFail inconsistent with exceptions

### ISSUE THREAD

**Issue by DavideFauri** [nomeata/tasty-expected-failure#23]
Hello,

I'm having some trouble with `expectFail` when the cause of the failure is an (expected) exception.
Specifically, applying it to a `testProperty` works fine, but it doesn't if I apply it to a `testCase`.

In this repository there is a working example of what I mean: [expectFail-test](https://github.com/DavideFauri/expectFail-test)

At the moment my hacky solution is to use `wrapTest` to try to catch all exceptions and then handle them by their printed representation, which feels very fragile:

```haskell
expectException :: String -> TestTree -> TestTree
expectException s = expectExceptions [s]

expectExceptions :: [String] -> TestTree -> TestTree
expectExceptions prefixes = wrapTest (handleJust selector handler)
  where
    selector :: SomeException -> Maybe SomeException
    selector e
      | not . null . prefixesMatching $ e = Just e
      | otherwise = Nothing
    handler e =
      pure
        Result
          { resultOutcome = Success,
            resultDescription = "Exception matches: " <> (intercalate " OR " . map quoted) (prefixesMatching e),
            resultShortDescription = "FAIL (expected)",
            resultTime = 0
          }
    prefixesMatching e = filter (`isPrefixOf` show e) prefixes
    quoted s = "\"" <> s <> "\""
```

Indeed, it only solves the cases where `expectFail` does not work, and it does not work where `expectFail` operates as intended.

My understanding so far is that `testProperty` somehow catches all exceptions and returns a `Failure` result, while `testCase` does no such thing and raises an Exception.
Is there a way to have a (robust) wrapper of TestTree so it can catch Exceptions consistently?

**Comment by nomeata** [comment]
@kquick looked at such problems previously, see https://github.com/nomeata/tasty-expected-failure/pull/18. Does your version contain that path?

>  Is there a way to have a (robust) wrapper of TestTree so it can catch Exceptions consistently?

I don’t know, maybe @feuerbach can advise?

**Comment by nomeata** [comment]
Maybe `testCase` needs to do something like this: https://github.com/feuerbach/tasty-golden/pull/16

**Comment by nomeata** [comment]
Also see this discussion for background:https://github.com/feuerbach/tasty/issues/125

**Comment by kquick** [comment]
I do believe this is fixed by #18 . 

@DavideFauri , the configuration you are using seems to be referencing stack's lts-16.23, which contains tasty-expected-failure version 0.11.1.2 which was from Aug 2019 and pre-dates the fixes in #18.  If you upgrade your version of tasty-expected-failure, I expect your issues will be resolved, and please post back here if that is not the case.

That said, the updated tasty-expected-failure does have to employ some unsavory techniques which could be eliminated if there were some corresponding updates in tasty itself.

**Comment by DavideFauri** [comment]
Thanks, I never thought about stackage having an older version... now it all makes sense! And here I was, furiously looking at the documentation on hackage and wondering why it wouldn't work... haha!

The fun part was, I implemented my solution based on https://github.com/nomeata/tasty-expected-failure/pull/18

I guess I can close this issue now :D

**Comment by nomeata** [comment]
Nevertheless, thanks for reporting
