### ISSUE TITLE
Exception throwing tests still fail

### ISSUE THREAD

**Issue by expipiplus1** [nomeata/tasty-expected-failure#3]
The test `error "fail"` wrapped in `expectFail` will still be marked as failing.

**Comment by nomeata** [comment]
Hi. Can you give a more complete example of how you are running your test?

**Comment by expipiplus1** [comment]
Here is a complete example using `tasty-golden`
https://github.com/expipiplus1/tasty-expected-failure-exception

**Comment by expipiplus1** [comment]
I think this is a problem in `tasty-golden`. But it would be nice if `tasty-expected-failure` dealt with these cases too.

**Comment by nomeata** [comment]
Hmm; I’d rather not add code to work around issues in other packages, if there is a chance to fix them there properly.

I guess the first step is to get @feuerbach involved and clarify what the contract for the [IsTest](http://hackage.haskell.org/package/tasty-0.11.0.1/docs/Test-Tasty-Providers.html#t:IsTest) class is: Should all exceptions of the code to test be caught by the `run` implementation, or the caller?

(I hope that it’s `run`’s responsibility to catch errors, and only throw exceptions, if at all, if something is wrong with the test suite.)

Once that is decided, then either `tasty-golden` needs to be improved, or this package gets your proposed change.
