### ISSUE TITLE
`expectFail` and timed-out tests

### ISSUE THREAD

**Issue by bezirg** [nomeata/tasty-expected-failure#6]
Can `expectFail` turn timeout tests to successful too?

Right now, the following code will not succeed:

``` haskell
import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.ExpectedFailure (expectFail)
import Control.Concurrent (threadDelay)

main = defaultMain $
        localOption (mkTimeout 1000000) $  -- 1s
          expectFail $ testCase "test1" (threadDelay 2000000) -- 2s
```

**Comment by nomeata** [comment]
I would say that this should work, but it might require coordination with the tasty code, or might simply not be possible, depending on the design of tasty. Patches welcome!

**Comment by nomeata** [comment]
Closing as per https://github.com/nomeata/tasty-expected-failure/pull/18#issuecomment-663073790
