### ISSUE TITLE
setup/teardown is executed for ignored tests?

### ISSUE THREAD

**Issue by pheaver** [nomeata/tasty-expected-failure#7]
Hello, it appears that `ignoreTest t` executes any setup/teardown (via `withResource`). Is this intentional?

I don't think that's desired behavior for us. The setup and teardown are part of the test that we need to skip (e.g. in one case, we want to use a flag to disable a test whose `withResource` call would blow up).

**Comment by nomeata** [comment]
Yes, that sounds sensible. Patch welcome!

**Comment by pheaver** [comment]
This might be difficult to do, since you can't preserve the `TestTree` without executing the function provided to `withResource`:

```
forall a . WithResource (ResourceSpec a) (IO a -> TestTree)
```

I ended up doing something like this:

```
  askOption $ \(MyFlag b) -> if b
                                then withResource test
                                else ignoreTest $ test $ return dummy
```

Perhaps the practical thing to do is just document this behavior of `ignoreTest`?

**Comment by nomeata** [comment]
Yes, that would be an improvement. PR welcome :-)

**Comment by pheaver** [comment]
https://github.com/nomeata/tasty-expected-failure/pull/8

**Comment by nomeata** [comment]
Thanks!
